<a href="https://colab.research.google.com/github/yuliia-naumeniuk/ab-testing-statistical-analysis/blob/main/A_B_Testing_Statistical_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Connecting to the Database**

In [ ]:
# Installing a library to work with Google BigQuery
!pip install --upgrade google-cloud-bigquery

# Libraries
from google.colab import auth
from google.cloud import bigquery
import pandas as pd
import statsmodels.api as sm

# Authentication
auth.authenticate_user()

# Creating a BigQuery client
client = bigquery.Client(project="data-analytics-mate")

Requirement already satisfied: google-cloud-bigquery in /usr/local/lib/python3.12/dist-packages (3.40.1)
Requirement already satisfied: google-api-core<3.0.0,>=2.11.1 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (2.30.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.47.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.8.0)
Requirement already satisfied: packaging>=24.2.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (26.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.32.4)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.72.0)
Requirement already satisfied: protobuf<7.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.11.1->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.27.1)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.78.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.71.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (4.9.1)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.8.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2026.1.4)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (4.15.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.6.2)

In [ ]:
# SQL query
query = """
WITH
 session_info AS (
   SELECT
     s.date,
     s.ga_session_id,
     sp.country,
     sp.device,
     sp.continent,
     sp.channel,
     ab.test,
     ab.test_group
   FROM `DA.ab_test` ab
   JOIN `DA.session` s
     ON ab.ga_session_id = s.ga_session_id
   JOIN `DA.session_params` sp
     ON sp.ga_session_id = ab.ga_session_id
 ),
 session_with_orders AS (
   SELECT
     session_info.date,
     session_info.country,
     session_info.device,
     session_info.continent,
     session_info.channel,
     session_info.test,
     session_info.test_group,
     COUNT(DISTINCT o.ga_session_id) AS session_with_orders
   FROM `DA.order` o
   JOIN session_info
     ON o.ga_session_id = session_info.ga_session_id
   GROUP BY
     session_info.date,
     session_info.country,
     session_info.device,
     session_info.continent,
     session_info.channel,
     session_info.test,
     session_info.test_group
 ),
 event AS (
   SELECT
     session_info.date,
     session_info.country,
    session_info.device,
     session_info.continent,
     session_info.channel,
     session_info.test,
     session_info.test_group,
     ep.event_name,
     COUNT(ep.ga_session_id) AS event_cnt
   FROM `DA.event_params` ep
   JOIN session_info
     ON ep.ga_session_id = session_info.ga_session_id
   GROUP BY
     session_info.date,
     session_info.country,
     session_info.device,
     session_info.continent,
     session_info.channel,
     session_info.test,
     session_info.test_group,
     ep.event_name
 ),
 session AS (
   SELECT
     session_info.date,
     session_info.country,
     session_info.device,
     session_info.continent,
     session_info.channel,
     session_info.test,
     session_info.test_group,
     COUNT(DISTINCT session_info.ga_session_id) AS session_cnt
   FROM session_info
 GROUP BY
     session_info.date,
     session_info.country,
     session_info.device,
     session_info.continent,
     session_info.channel,
     session_info.test,
     session_info.test_group
 ),
 account AS (
   SELECT
     session_info.date,
     session_info.country,
     session_info.device,
     session_info.continent,
     session_info.channel,
     session_info.test,
     session_info.test_group,
     COUNT(DISTINCT acs.ga_session_id) AS new_account_cnt
   FROM `DA.account_session` acs
   JOIN session_info
     ON acs.ga_session_id = session_info.ga_session_id
   GROUP BY
     session_info.date,
     session_info.country,
     session_info.device,
     session_info.continent,
     session_info.channel,
     session_info.test,
     session_info.test_group
 )
SELECT
 session_with_orders.date,
 session_with_orders.country,
 session_with_orders.device,
 session_with_orders.continent,
 session_with_orders.channel,
 session_with_orders.test,
 session_with_orders.test_group,
 'session with orders' AS event_name,
 session_with_orders.session_with_orders AS value
FROM session_with_orders
UNION ALL
SELECT
 event.date,
 event.country,
 event.device,
 event.continent,
 event.channel,
 event.test,
 event.test_group,
 event_name,
 event_cnt AS value
FROM event
UNION ALL
SELECT
 session.date,
 session.country,
 session.device,
 session.continent,
 session.channel,
 session.test,
 session.test_group,
 'session' AS event_name,
 session_cnt AS value
FROM session
UNION ALL
SELECT
 account.date,
 account.country,
 account.device,
 account.continent,
 account.channel,
 account.test,
 account.test_group,
 'new account' AS event_name,
 new_account_cnt AS value
FROM account
  """

In [ ]:
# Executing the query
query_job = client.query(query)  # Executing the SQL query
results = query_job.result()  # Waiting for the query to complete


# Converting results to a DataFrame
df = results.to_dataframe()


# Displaying the results
df.head()

,date,country,device,continent,channel,test,test_group,event_name,value
0,2020-11-02,North Macedonia,desktop,Europe,Direct,2,1,session with orders,1
1,2020-11-03,New Zealand,desktop,Oceania,Direct,2,2,session with orders,1
2,2020-11-04,Bulgaria,mobile,Europe,Paid Search,2,1,session with orders,1
3,2020-11-04,Kuwait,mobile,Asia,Organic Search,2,2,session with orders,1
4,2020-11-05,Serbia,desktop,Europe,Social Search,2,2,session with orders,1

# **2. Overall Test Significance**

In [ ]:
# Metrics setup
metrics = ["add_payment_info", "add_shipping_info", "begin_checkout", "new account"]

results = []

In [ ]:
# Aggregate Events by Test and Test Group
total_df = df.groupby(["test", "test_group", "event_name"])["value"].sum().reset_index()

total_df.head()

   test  test_group         event_name  value
0     1           1   add_payment_info   1988
1     1           1  add_shipping_info   3034
2     1           1        add_to_cart   1395
3     1           1     begin_checkout   3784
4     1           1              click    368

In [ ]:
# Iterate through Tests
for test in total_df["test"].unique():
  test_data = total_df[total_df["test"] == test]

  print(f"\n ---Test {test}--- ")


  # Iterate through Metrics
  for metric in metrics:

    control_value = test_data[(test_data["test_group"] == 1) & (test_data["event_name"] == metric)]["value"].iloc[0]

    control_sessions = test_data[(test_data["test_group"] == 1) & (test_data["event_name"] == "session")]["value"].iloc[0]

    test_value = test_data[(test_data["test_group"] == 2) & (test_data["event_name"] == metric)]["value"].iloc[0]

    test_sessions = test_data[(test_data["test_group"] == 2) & (test_data["event_name"] == "session")]["value"].iloc[0]


    # Z-Test calculation
    z_stat, p_value = sm.stats.proportions_ztest([test_value, control_value], [test_sessions, control_sessions])


    # Metric change calculation
    metric_change = ((test_value / test_sessions) - (control_value / control_sessions)) / (control_value / control_sessions) * 100


    # Save results
    results.append({
    "test_number": test,
    "metric": metric,
    "numerator_event": metric,
    "denominator_event": "session",
    "numerator_control": control_value,
    "denominator_control": control_sessions,
    "conversion_rate_control": control_value / control_sessions,
    "numerator_test": test_value,
    "denominator_test": test_sessions,
    "conversion_rate_test": test_value / test_sessions,
    "metric_change_%": metric_change,
    "z_stat": z_stat,
    "p_value": p_value,
    "significant": p_value < 0.05
})

 ---Test 1---

 ---Test 2---

 ---Test 3---

 ---Test 4---

# **3. Statistical Significance by Device**

In [ ]:
# Aggregate Events by Test, Test Group and Device
device_df = df.groupby(["test", "test_group", "device", "event_name"])["value"].sum().reset_index()

device_df.head()

   test  test_group   device         event_name  value
0     1           1  desktop   add_payment_info   1130
1     1           1  desktop  add_shipping_info   1711
2     1           1  desktop        add_to_cart    821
3     1           1  desktop     begin_checkout   2108
4     1           1  desktop              click    246

In [ ]:
# Iterate through Tests
for test in device_df["test"].unique():
  test_data = device_df[device_df["test"] == test]


  # Iterate through Devices
  for device in test_data["device"].unique():

        device_data = test_data[test_data["device"] == device]

        print(f"\n--- Test {test} | Device: {device} ---")


        # Iterate through Metrics
        for metric in metrics:

          control_value = device_data[(device_data["test_group"] == 1) & (device_data["event_name"] == metric)]["value"].iloc[0]

          control_sessions = device_data[(device_data["test_group"] == 1) & (device_data["event_name"] == "session")]["value"].iloc[0]

          test_value = device_data[(device_data["test_group"] == 2) & (device_data["event_name"] == metric)]["value"].iloc[0]

          test_sessions = device_data[(device_data["test_group"] == 2) & (device_data["event_name"] == "session")]["value"].iloc[0]


          # Z-Test calculation
          z_stat, p_value = sm.stats.proportions_ztest([test_value, control_value], [test_sessions, control_sessions])


          print(f"Metric: {metric} | p-value: {p_value}")

--- Test 1 | Device: desktop ---
Metric: add_payment_info | p-value: 0.007209741371215498
Metric: add_shipping_info | p-value: 0.0003357584652017076
Metric: begin_checkout | p-value: 2.9541814920943097e-06
Metric: new account | p-value: 0.41152570800346633

--- Test 1 | Device: mobile ---
Metric: add_payment_info | p-value: 0.0007006374762030875
Metric: add_shipping_info | p-value: 0.867065231958409
Metric: begin_checkout | p-value: 0.7009567356723287
Metric: new account | p-value: 0.13374756193786455

--- Test 1 | Device: tablet ---
Metric: add_payment_info | p-value: 0.04586782579263077
Metric: add_shipping_info | p-value: 0.0914639928431928
Metric: begin_checkout | p-value: 0.014906985506589771
Metric: new account | p-value: 0.8713411093173797

--- Test 2 | Device: desktop ---
Metric: add_payment_info | p-value: 0.06943375930883558
Metric: add_shipping_info | p-value: 0.07925229942804458
Metric: begin_checkout | p-value: 0.004507241652049557
Metric: new account | p-value: 0.47635598695904835

--- Test 2 | Device: mobile ---
Metric: add_payment_info | p-value: 0.9206922797202424
Metric: add_shipping_info | p-value: 0.39936585774587097
Metric: begin_checkout | p-value: 0.11748369217113229
Metric: new account | p-value: 0.07052980522198629

--- Test 2 | Device: tablet ---
Metric: add_payment_info | p-value: 0.6558638783538968
Metric: add_shipping_info | p-value: 0.4835423611906613
Metric: begin_checkout | p-value: 0.10757988225238578
Metric: new account | p-value: 0.9602910655090428

--- Test 3 | Device: desktop ---
Metric: add_payment_info | p-value: 0.3241079008683533
Metric: add_shipping_info | p-value: 0.3329107263942983
Metric: begin_checkout | p-value: 0.325603211147243
Metric: new account | p-value: 0.3316118010189646

--- Test 3 | Device: mobile ---
Metric: add_payment_info | p-value: 0.9846284069920155
Metric: add_shipping_info | p-value: 0.48081550783345417
Metric: begin_checkout | p-value: 0.027318646897485362
Metric: new account | p-value: 0.9700601751499698

--- Test 3 | Device: tablet ---
Metric: add_payment_info | p-value: 0.5098279543022014
Metric: add_shipping_info | p-value: 0.0990393134755965
Metric: begin_checkout | p-value: 0.00457821611056783
Metric: new account | p-value: 0.608120898614203

--- Test 4 | Device: desktop ---
Metric: add_payment_info | p-value: 0.010836305754479095
Metric: add_shipping_info | p-value: 0.00930526804149035
Metric: begin_checkout | p-value: 0.00017384931639323234
Metric: new account | p-value: 0.03585262729559277

--- Test 4 | Device: mobile ---
Metric: add_payment_info | p-value: 0.11551748599497738
Metric: add_shipping_info | p-value: 0.365054456873658
Metric: begin_checkout | p-value: 0.026855532467888354
Metric: new account | p-value: 0.3023531194295901

--- Test 4 | Device: tablet ---
Metric: add_payment_info | p-value: 2.691948781951007e-05
Metric: add_shipping_info | p-value: 0.011266798783670018
Metric: begin_checkout | p-value: 0.00045893502294236914
Metric: new account | p-value: 0.4293739937780411

# **4. Statistical Significance by Channel**

In [ ]:
# Aggregate Events by Test, Test Group and Channel
channel_df = df.groupby(["test", "test_group", "channel", "event_name"])["value"].sum().reset_index()

channel_df.head()

   test  test_group channel         event_name  value
0     1           1  Direct   add_payment_info    392
1     1           1  Direct  add_shipping_info    664
2     1           1  Direct        add_to_cart    269
3     1           1  Direct     begin_checkout    823
4     1           1  Direct              click     79

In [ ]:
# Iterate through Tests
for test in channel_df["test"].unique():
  test_data = channel_df[channel_df["test"] == test]


  # Iterate through Channels
  for channel in test_data["channel"].unique():

        channel_data = test_data[test_data["channel"] == channel]

        print(f"\n--- Test {test} | Channel: {channel} ---")


        # Iterate through Metrics
        for metric in metrics:

          control_value = channel_data[(channel_data["test_group"] == 1) & (channel_data["event_name"] == metric)]["value"].iloc[0]

          control_sessions = channel_data[(channel_data["test_group"] == 1) & (channel_data["event_name"] == "session")]["value"].iloc[0]

          test_value = channel_data[(channel_data["test_group"] == 2) & (channel_data["event_name"] == metric)]["value"].iloc[0]

          test_sessions = channel_data[(channel_data["test_group"] == 2) & (channel_data["event_name"] == "session")]["value"].iloc[0]


          # Z-Test calculation
          z_stat, p_value = sm.stats.proportions_ztest([test_value, control_value], [test_sessions, control_sessions])


          print(f"Metric: {metric} | p-value: {p_value}")

--- Test 1 | Channel: Direct ---
Metric: add_payment_info | p-value: 2.7285656989392044e-06
Metric: add_shipping_info | p-value: 0.040295440378197364
Metric: begin_checkout | p-value: 0.0028210870432094437
Metric: new account | p-value: 0.37885982126254425

--- Test 1 | Channel: Organic Search ---
Metric: add_payment_info | p-value: 0.0001909045129292049
Metric: add_shipping_info | p-value: 0.024127398901353108
Metric: begin_checkout | p-value: 0.030621596905618862
Metric: new account | p-value: 0.9619193439402388

--- Test 1 | Channel: Paid Search ---
Metric: add_payment_info | p-value: 0.029451531682692326
Metric: add_shipping_info | p-value: 0.6050741043001047
Metric: begin_checkout | p-value: 0.7352929738262673
Metric: new account | p-value: 0.26258737187988956

--- Test 1 | Channel: Social Search ---
Metric: add_payment_info | p-value: 0.31206144881364284
Metric: add_shipping_info | p-value: 0.058208620675484775
Metric: begin_checkout | p-value: 0.20374842306540475
Metric: new account | p-value: 0.500782701424417

--- Test 1 | Channel: Undefined ---
Metric: add_payment_info | p-value: 1.3774697351488817e-08
Metric: add_shipping_info | p-value: 2.609055609478326e-09
Metric: begin_checkout | p-value: 1.8208174487320637e-13
Metric: new account | p-value: 0.008584349755047103

--- Test 2 | Channel: Direct ---
Metric: add_payment_info | p-value: 0.8605679343405472
Metric: add_shipping_info | p-value: 0.3672936064578117
Metric: begin_checkout | p-value: 0.7045260263577747
Metric: new account | p-value: 0.581049015892859

--- Test 2 | Channel: Organic Search ---
Metric: add_payment_info | p-value: 0.004798186069486433
Metric: add_shipping_info | p-value: 0.05205589839540171
Metric: begin_checkout | p-value: 0.007899320372393971
Metric: new account | p-value: 0.11665809528107429

--- Test 2 | Channel: Paid Search ---
Metric: add_payment_info | p-value: 0.24461457417672938
Metric: add_shipping_info | p-value: 0.03950403035285792
Metric: begin_checkout | p-value: 0.03666222910101377
Metric: new account | p-value: 0.9721095910165564

--- Test 2 | Channel: Social Search ---
Metric: add_payment_info | p-value: 0.041452759591752215
Metric: add_shipping_info | p-value: 0.8754193004193286
Metric: begin_checkout | p-value: 0.3511042081159448
Metric: new account | p-value: 0.3223750385746258

--- Test 2 | Channel: Undefined ---
Metric: add_payment_info | p-value: 8.48317300586228e-05
Metric: add_shipping_info | p-value: 0.0006420331307766895
Metric: begin_checkout | p-value: 0.0001513829646545486
Metric: new account | p-value: 0.4612795113583448

--- Test 3 | Channel: Direct ---
Metric: add_payment_info | p-value: 0.09368902060429311
Metric: add_shipping_info | p-value: 0.09643083561379294
Metric: begin_checkout | p-value: 0.11732144936155614
Metric: new account | p-value: 0.4473078179356218

--- Test 3 | Channel: Organic Search ---
Metric: add_payment_info | p-value: 0.3550260489067768
Metric: add_shipping_info | p-value: 0.2117951243518308
Metric: begin_checkout | p-value: 0.0008339583021256555
Metric: new account | p-value: 0.3612848368953109

--- Test 3 | Channel: Paid Search ---
Metric: add_payment_info | p-value: 0.6898722747103019
Metric: add_shipping_info | p-value: 0.21093369701588538
Metric: begin_checkout | p-value: 0.04268770059484565
Metric: new account | p-value: 0.6892447479652668

--- Test 3 | Channel: Social Search ---
Metric: add_payment_info | p-value: 0.7212394819454464
Metric: add_shipping_info | p-value: 0.8900400288749909
Metric: begin_checkout | p-value: 0.5759931528979227
Metric: new account | p-value: 0.5996907220265539

--- Test 3 | Channel: Undefined ---
Metric: add_payment_info | p-value: 0.04229248243650399
Metric: add_shipping_info | p-value: 0.012528232442341346
Metric: begin_checkout | p-value: 0.0011347326470617332
Metric: new account | p-value: 0.6548466815949319

--- Test 4 | Channel: Direct ---
Metric: add_payment_info | p-value: 0.08141278801104239
Metric: add_shipping_info | p-value: 0.2588183878895698
Metric: begin_checkout | p-value: 0.4222129098783486
Metric: new account | p-value: 0.019009953309091932

--- Test 4 | Channel: Organic Search ---
Metric: add_payment_info | p-value: 0.6111921918324118
Metric: add_shipping_info | p-value: 0.035091993122770726
Metric: begin_checkout | p-value: 0.00015981536137634823
Metric: new account | p-value: 0.02912463849534477

--- Test 4 | Channel: Paid Search ---
Metric: add_payment_info | p-value: 0.8211985195846756
Metric: add_shipping_info | p-value: 0.5189343346529449
Metric: begin_checkout | p-value: 0.008046238061082652
Metric: new account | p-value: 0.7911308279021608

--- Test 4 | Channel: Social Search ---
Metric: add_payment_info | p-value: 0.000493685099920661
Metric: add_shipping_info | p-value: 0.04840233355074842
Metric: begin_checkout | p-value: 0.004311885667456535
Metric: new account | p-value: 0.5305013400576115

--- Test 4 | Channel: Undefined ---
Metric: add_payment_info | p-value: 0.06833182389637445
Metric: add_shipping_info | p-value: 0.7794573012677897
Metric: begin_checkout | p-value: 0.7065791628856082
Metric: new account | p-value: 0.6550612595414917

# **5. Statistical Significance by Continent**

In [ ]:
# Aggregate Events by Test, Test Group and Continent
continent_df = df.groupby(["test", "test_group", "continent", "event_name"])["value"].sum().reset_index()

continent_df.head()

   test  test_group  continent         event_name  value
0     1           1  (not set)   add_payment_info      7
1     1           1  (not set)  add_shipping_info      4
2     1           1  (not set)        add_to_cart      3
3     1           1  (not set)     begin_checkout      4
4     1           1  (not set)              click      1

In [ ]:
# Iterate through Tests
for test in continent_df["test"].unique():
  test_data = continent_df[continent_df["test"] == test]


  # Iterate through Continents
  for continent in test_data["continent"].unique():

        continent_data = test_data[test_data["continent"] == continent]

        print(f"\n--- Test {test} | Continent: {continent} ---")


        # Iterate through Metrics
        for metric in metrics:

          control_value = continent_data[(continent_data["test_group"] == 1) & (continent_data["event_name"] == metric)]["value"].iloc[0]

          control_sessions = continent_data[(continent_data["test_group"] == 1) & (continent_data["event_name"] == "session")]["value"].iloc[0]

          test_value = continent_data[(continent_data["test_group"] == 2) & (continent_data["event_name"] == metric)]["value"].iloc[0]

          test_sessions = continent_data[(continent_data["test_group"] == 2) & (continent_data["event_name"] == "session")]["value"].iloc[0]


          # Z-Test calculation
          z_stat, p_value = sm.stats.proportions_ztest([test_value, control_value], [test_sessions, control_sessions])


          print(f"Metric: {metric} | p-value: {p_value}")

--- Test 1 | Continent: (not set) ---
Metric: add_payment_info | p-value: 0.48668867355025014
Metric: add_shipping_info | p-value: 0.02654503387641662
Metric: begin_checkout | p-value: 0.0002105143780896666
Metric: new account | p-value: 0.35683904415325407

--- Test 1 | Continent: Africa ---
Metric: add_payment_info | p-value: 0.3581959726668148
Metric: add_shipping_info | p-value: 0.14812541880677874
Metric: begin_checkout | p-value: 0.03089358445102105
Metric: new account | p-value: 0.6694076814720262

--- Test 1 | Continent: Americas ---
Metric: add_payment_info | p-value: 0.05923178099558561
Metric: add_shipping_info | p-value: 0.27942702228096183
Metric: begin_checkout | p-value: 0.27793953584638764
Metric: new account | p-value: 0.008826843842463641

--- Test 1 | Continent: Asia ---
Metric: add_payment_info | p-value: 0.5702422481017848
Metric: add_shipping_info | p-value: 0.21898733380776259
Metric: begin_checkout | p-value: 0.15248585784948884
Metric: new account | p-value: 0.45727841568459116

--- Test 1 | Continent: Europe ---
Metric: add_payment_info | p-value: 1.6931752371532812e-06
Metric: add_shipping_info | p-value: 0.012444825223304968
Metric: begin_checkout | p-value: 0.003906598111157333
Metric: new account | p-value: 0.7154772577516382

--- Test 1 | Continent: Oceania ---
Metric: add_payment_info | p-value: 0.6797794846465908
Metric: add_shipping_info | p-value: 0.1267084612612821
Metric: begin_checkout | p-value: 0.019893626513698515
Metric: new account | p-value: 0.3461063557480396

--- Test 2 | Continent: (not set) ---
Metric: add_payment_info | p-value: 0.06491508370734582
Metric: add_shipping_info | p-value: 0.8745963050660519
Metric: begin_checkout | p-value: 0.21351696863924352
Metric: new account | p-value: 0.891708706146546

--- Test 2 | Continent: Africa ---
Metric: add_payment_info | p-value: 0.005187849828190252
Metric: add_shipping_info | p-value: 0.0032475695881740907
Metric: begin_checkout | p-value: 0.00029470018264416326
Metric: new account | p-value: 0.652059238606111

--- Test 2 | Continent: Americas ---
Metric: add_payment_info | p-value: 0.0171938762585697
Metric: add_shipping_info | p-value: 0.7765444929742644
Metric: begin_checkout | p-value: 0.8787978438452103
Metric: new account | p-value: 0.9969070123921847

--- Test 2 | Continent: Asia ---
Metric: add_payment_info | p-value: 0.08606663540593125
Metric: add_shipping_info | p-value: 0.3395097315499399
Metric: begin_checkout | p-value: 0.032122255416676224
Metric: new account | p-value: 0.3512619777824848

--- Test 2 | Continent: Europe ---
Metric: add_payment_info | p-value: 0.008029781575731814
Metric: add_shipping_info | p-value: 0.9682311102876453
Metric: begin_checkout | p-value: 0.4453451985513768
Metric: new account | p-value: 0.6412870909173638

--- Test 2 | Continent: Oceania ---
Metric: add_payment_info | p-value: 0.27304201794266103
Metric: add_shipping_info | p-value: 0.0017706186728919807
Metric: begin_checkout | p-value: 0.0004598707379871312
Metric: new account | p-value: 0.8379518988685069

--- Test 3 | Continent: (not set) ---
Metric: add_payment_info | p-value: 0.1778514103878469
Metric: add_shipping_info | p-value: 0.8830898319829326
Metric: begin_checkout | p-value: 0.5571089800924072
Metric: new account | p-value: 0.7305461437661251

--- Test 3 | Continent: Africa ---
Metric: add_payment_info | p-value: 0.41462828357687864
Metric: add_shipping_info | p-value: 0.9164490838087899
Metric: begin_checkout | p-value: 0.5371713080014267
Metric: new account | p-value: 0.599421476716897

--- Test 3 | Continent: Americas ---
Metric: add_payment_info | p-value: 0.2810476891301985
Metric: add_shipping_info | p-value: 0.20090005629552665
Metric: begin_checkout | p-value: 0.006039983884910555
Metric: new account | p-value: 0.7047527905763891

--- Test 3 | Continent: Asia ---
Metric: add_payment_info | p-value: 0.406564214689097
Metric: add_shipping_info | p-value: 0.4547938643158882
Metric: begin_checkout | p-value: 0.37518332115474096
Metric: new account | p-value: 0.27689105235271094

--- Test 3 | Continent: Europe ---
Metric: add_payment_info | p-value: 0.35836789112723166
Metric: add_shipping_info | p-value: 0.958415595492988
Metric: begin_checkout | p-value: 0.7442210642723679
Metric: new account | p-value: 0.5493994179711583

--- Test 3 | Continent: Oceania ---
Metric: add_payment_info | p-value: 0.16477295022780114
Metric: add_shipping_info | p-value: 0.2459142647258854
Metric: begin_checkout | p-value: 0.055302672952322794
Metric: new account | p-value: 0.8874844678345375

--- Test 4 | Continent: (not set) ---
Metric: add_payment_info | p-value: 0.003068924881785101
Metric: add_shipping_info | p-value: 0.012379101773007696
Metric: begin_checkout | p-value: 0.0007711472126445931
Metric: new account | p-value: 0.8891784205251294

--- Test 4 | Continent: Africa ---
Metric: add_payment_info | p-value: 0.8752669333482194
Metric: add_shipping_info | p-value: 0.05424683587351208
Metric: begin_checkout | p-value: 0.003784449911260791
Metric: new account | p-value: 0.09008464191291486

--- Test 4 | Continent: Americas ---
Metric: add_payment_info | p-value: 0.9647129932315217
Metric: add_shipping_info | p-value: 0.6618484497474988
Metric: begin_checkout | p-value: 0.6792394302679785
Metric: new account | p-value: 0.10867355442588318

--- Test 4 | Continent: Asia ---
Metric: add_payment_info | p-value: 0.9493535188184681
Metric: add_shipping_info | p-value: 0.751436383242345
Metric: begin_checkout | p-value: 0.5471128833291601
Metric: new account | p-value: 0.01816748146756498

--- Test 4 | Continent: Europe ---
Metric: add_payment_info | p-value: 0.01779241145385819
Metric: add_shipping_info | p-value: 0.0027253460007450703
Metric: begin_checkout | p-value: 1.2355678503675292e-06
Metric: new account | p-value: 0.9305070760966762

--- Test 4 | Continent: Oceania ---
Metric: add_payment_info | p-value: 0.000572489186134029
Metric: add_shipping_info | p-value: 0.010588525250408274
Metric: begin_checkout | p-value: 8.401002070156756e-06
Metric: new account | p-value: 0.2582726086640852

# **6. Tableau Dashboard**

In [ ]:
# Create results DataFrame
results_df = pd.DataFrame(results)

results_df.head()

,test_number,metric,numerator_event,denominator_event,numerator_control,denominator_control,conversion_rate_control,numerator_test,denominator_test,conversion_rate_test,metric_change_%,z_stat,p_value,significant
0,1,add_payment_info,add_payment_info,session,1988,45362,0.043825,2229,45193,0.049322,12.542021,3.924884,0.000087,True
1,1,add_shipping_info,add_shipping_info,session,3034,45362,0.066884,3221,45193,0.071272,6.560481,2.603571,0.009226,True
2,1,begin_checkout,begin_checkout,session,3784,45362,0.083418,4021,45193,0.088974,6.660587,2.978783,0.002894,True
3,1,new account,new account,session,3823,45362,0.084278,3681,45193,0.081451,-3.354299,-1.542883,0.122859,False
4,2,add_payment_info,add_payment_info,session,2344,50637,0.046290,2409,50244,0.047946,3.576911,1.240994,0.214608,False

In [ ]:
# Saving data for visualization in Tableau


# Excel file
from google.colab import drive

drive.mount("/content/drive")

results_df.to_excel("/content/drive/MyDrive/ab_test_results.xlsx", index=False)


# CSV file
results_df.to_csv("/content/drive/MyDrive/ab_test_results.csv", index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

A/B Test Results:

[Excel File](https://docs.google.com/spreadsheets/d/1myCgcQbqS0zzngGpj4sCiOrZLCN5jy82/edit?usp=drive_link&ouid=112977218335542423372&rtpof=true&sd=true)

[СSV File](https://drive.google.com/file/d/1OwODKHYD_JW_l_NlY6_S57f6gTgzNTUS/view?usp=drive_link)

Tableau Dashboard:

[View in Tableau](https://public.tableau.com/views/ABTest_17717709255380/ABTest?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link)

# **7. Overall Conclusions**

(EN)

**Test 1:**

A statistically significant positive effect was found for the metrics **add_payment_info**, **add_shipping_info**, and **begin_checkout** (p-value < 0.05).

The **new account** metric was not statistically significant.

**Test 2:**

For all analyzed metrics, the p-values are above 0.05.

This means that no statistically significant differences were found between the control group and the test group.

**Test 3:**

A statistically significant negative effect was found for the **begin_checkout** metric (p-value = 0.012 < 0.05).

The other metrics were not statistically significant.

**Test 4:**

A statistically significant negative effect was found for the **begin_checkout** metric (p-value = 0.046 < 0.05) and the **new account** metric (p-value = 0.018 < 0.05).

The **add_payment_info** and **add_shipping_info** metrics were not statistically significant.

(PL)

**Test 1:**

Wykryto statystycznie istotny pozytywny wpływ na metryki ***add_payment_info***, ***add_shipping_info*** oraz ***begin_checkout*** (p-value < 0,05).

Metryka ***new account*** nie wykazała istotności statystycznej.

**Test 2:**

Dla wszystkich analizowanych metryk wartości p-value przekraczają 0,05.

Oznacza to, że nie stwierdzono statystycznie istotnych różnic między grupą kontrolną a grupą testową.

**Test 3:**

Wykryto statystycznie istotny negatywny wpływ na metrykę ***begin_checkout*** (p-value = 0,012 < 0,05).

Pozostałe metryki nie wykazały istotności statystycznej.

**Test 4:**

Odnotowano statystycznie istotny negatywny wpływ na metryki ***begin_checkout*** (p-value = 0,046 < 0,05) oraz ***new account*** (p-value = 0,018 < 0,05).

Metryki ***add_payment_info*** oraz ***add_shipping_info*** pozostały statystycznie nieistotne.